# -*- coding: utf-8 -*-
"""Imersão_Dados_Alura.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JniPhFbHCaXjONZrbv56yjFKMlNS6FQX

# Imersão de Dados com Python

## Aula 1 - Análise de Dados com Pandas
"""

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

df.head(10)

df.info()

df.describe()

df.shape

linhas, colunas = df.shape[0], df.shape[1]
print(f"O DataFrame possui {linhas} linhas e {colunas} colunas.")

df.columns

df = df.rename(columns={
    'work_year': 'ano',
    'experience_level': 'senioridade',
    'employment_type': 'contrato',
    'job_title': 'cargo',
    'salary': 'salario',
    'salary_currency': 'moeda',
    'salary_in_usd': 'usd',
    'employee_residence': 'residencia',
    'remote_ratio': 'remoto',
    'company_location': 'empresa',
    'company_size': 'tamanho_empresa'
})

print("Novas colunas do DataFrame:")
print(df.columns)

df['senioridade'].value_counts()

df['contrato'].value_counts()

df['remoto'].value_counts()

df['tamanho_empresa'].value_counts()

senioridade = {
    'SE': 'Sênior',
    'MI': 'Pleno',
    'EN': 'Júnior',
    'EX': 'Executivo'
}

df['senioridade'] = df['senioridade'].replace(senioridade)

print("Novos valores da coluna 'senioridade' (traduzidos):")
df['senioridade'].value_counts()



contrato = {
    'FT': 'Tempo Integral',
    'CT': 'Contrato',
    'PT': 'Tempo Parcial',
    'FL': 'Freelancer'
}

df['contrato'] = df['contrato'].replace(contrato)

print("Novos valores da coluna 'contrato' (traduzidos):")
df['contrato'].value_counts()

tamanho_empresa = {
    'M': 'Média',
    'L': 'Grande',
    'S': 'Pequena'
}

df['tamanho_empresa'] = df['tamanho_empresa'].replace(tamanho_empresa)

print("Novos valores da coluna 'tamanho_empresa' (traduzidos):")
df['tamanho_empresa'].value_counts()

remoto = {
    0: 'Presencial',
    50: 'Híbrido',
    100: 'Remoto'
}

df['remoto'] = df['remoto'].replace(remoto)

print("Novos valores da coluna 'remoto' (traduzidos):")
df['remoto'].value_counts()

df.head()

df.describe(include='object')

"""## Imersão Dados com Python II
## Aula 2 - Limpeza de Dados com Pandas
"""

df.isnull().sum()

df['ano'].unique()

df[df.isnull().any(axis=1)]

"""### Criando um dataframe fictício para estudos"""

import numpy as np

# criando um dataframe para exemplificar a aplicação da média e mediana no preenchimento de valores nulos
df_salarios = pd.DataFrame({
    'nome': ['João', 'Maria', 'Pedro', 'Ana', 'Lucas'],
    'idade': [25, 30, 22, 28, 35],
    'cargo': ['Analista de Dados', 'Engenheiro de Software', 'Cientista de Dados', 'Analista de Marketing','Gerente de Projetos'],
    'salario': [6000, np.nan, 7500, np.nan, 19000],
})

# calculo da média salarial e substituição dos valores nulos pela média de salário, arredondando os valores
df_salarios['salario_media'] = df_salarios ['salario'].fillna(df_salarios['salario'].mean().round(2))

'''
calculo da mediana salarial e substituição dos valores nulos pela mediana de salário, arredondando os valores
'''
df_salarios['salario_mediana'] = df_salarios ['salario'].fillna(df_salarios['salario'].median())

df_salarios

df_temperaturas = pd.DataFrame({
    'cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Porto Alegre', 'Curitiba'],
    'temperatura': [25, np.nan, np.nan, 28, 35],
    'umidade': [80, 90, 70, 60, 50],
    'dia': ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta'],
})

df_temperaturas['preenchido_ffill'] = df_temperaturas['temperatura'].ffill()
df_temperaturas

df_temperaturas = pd.DataFrame({
    'cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Porto Alegre', 'Curitiba'],
    'temperatura': [25, np.nan, np.nan, 28, 35],
    'umidade': [80, 90, 70, 60, 50],
    'dia': ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta'],
})

df_temperaturas['preenchido_bfill'] = df_temperaturas['temperatura'].bfill()
df_temperaturas

df_cidades = pd.DataFrame({
    'cidade': ['São Paulo', np.nan, 'Belo Horizonte', 'Porto Alegre', np.nan],
    'nome': ['João', 'Maria', 'Pedro', 'Ana', 'Lucas'],
    'idade': [25, 30, 22, 28, 43],
})

df_cidades['cidade_preenchida'] = df_cidades['cidade'].fillna('Não informado')
df_cidades

df_tratado = df.dropna()

df_tratado.isnull().sum()

df_tratado.head()

df_tratado.info()

df_tratado = df_tratado.assign(ano = df_tratado['ano'].astype('int64'))



"""## Imersão Dados com Python II
Aula 3 - Visualização de Dados
"""

df_tratado.head()

import matplotlib.pyplot as plt
df_tratado['senioridade'].value_counts().plot(kind='bar', title = "Distribuição de Senioridade")
plt.show()

import seaborn as sns
sns.countplot(data=df_tratado, x='senioridade')
plt

sns.barplot(data=df_tratado, x='senioridade', y='usd')
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sns.barplot(data=df_tratado, x='senioridade', y='usd')
plt.title('Salário médio por Senioridade')
plt.xlabel('Senioridade')
plt.ylabel('Salário médio anual (USD)')
plt.show()

df_tratado.groupby('senioridade')['usd'].mean().sort_values(ascending=False).round(2)

ordem = df_tratado.groupby('senioridade')['usd'].mean().sort_values(ascending=False).round(2).index
ordem

plt.figure(figsize=(10, 6))
sns.barplot(data=df_tratado, x='senioridade', y='usd', order=ordem)
plt.title('Salário médio por Senioridade')
plt.xlabel('Senioridade')
plt.ylabel('Salário médio anual (USD)')
plt.show()

plt.figure(figsize=(8, 4))
sns.histplot(df_tratado['usd'],bins=50, kde=True)
plt.title('Distribuição salarial por ano')
plt.xlabel('Salário anual (USD)')
plt.ylabel('Frequência')
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x=df_tratado['usd'])
plt.title('Boxplot Salário')
plt.xlabel('Salário anual (USD)')
plt.show()

#ordem_senioridade = ['Executivo', 'Sênior', 'Pleno', 'Júnior']
ordem_senioridade = ['Júnior', 'Pleno', 'Sênior', 'Executivo']

plt.figure(figsize=(8,5))
sns.boxplot(x='senioridade', y='usd',data=df_tratado, order=ordem_senioridade)
plt.title('Boxplot da distribuição por Senioridade')
plt.xlabel('Salario em USD')
plt.show()

#ordem_senioridade = ['Executivo', 'Sênior', 'Pleno', 'Júnior']
ordem_senioridade = ['Júnior', 'Pleno', 'Sênior', 'Executivo']

plt.figure(figsize=(8,5))
sns.boxplot(x='senioridade', y='usd',data=df_tratado, order=ordem_senioridade, palette='Set2', hue='senioridade')
plt.title('Boxplot da distribuição por Senioridade')
plt.xlabel('Salario em USD')
plt.show()

import plotly.express as px

df_media_senioridade = df_tratado.groupby('senioridade')['usd'].mean().sort_values(ascending=False).round(2).reset_index()
fig = px.bar(
    df_media_senioridade,
    x='senioridade',
    y='usd',
    title='Média Salarial por Senioridade (Plotly)',
    labels={'senioridade': 'Nível de Senioridade', 'usd': 'Salário Médio Anual (USD)'},
    color='senioridade',
    category_orders={'senioridade': df_media_senioridade['senioridade'].tolist()}
)
fig.show()

remoto_contagem = df_tratado['remoto'].value_counts().reset_index()
#remoto_contagem

remoto_contagem.columns = ['tipo_trabalho', 'quantidade']

fig = px.pie(remoto_contagem,
             values='quantidade',
             names='tipo_trabalho',
             title='Proporção dos tipos de trabalho')
fig.show()

remoto_contagem = df_tratado['remoto'].value_counts().reset_index()
#remoto_contagem

remoto_contagem.columns = ['tipo_trabalho', 'quantidade']

fig = px.pie(remoto_contagem,
             values='quantidade',
             names='tipo_trabalho',
             title='Proporção dos tipos de trabalho',
             hole=0.5)
fig.show()

remoto_contagem = df_tratado['remoto'].value_counts().reset_index()
#remoto_contagem

remoto_contagem.columns = ['tipo_trabalho', 'quantidade']

fig = px.pie(remoto_contagem,
             values='quantidade',
             names='tipo_trabalho',
             title='Proporção dos tipos de trabalho',
             hole=0.5)
fig.update_traces(textposition='inside', textinfo='percent+label')
fig.show()

df_data_scientist = df_tratado[df_tratado['cargo'] == 'Data Scientist']

df_media_salario_pais = df_data_scientist.groupby('empresa')['usd'].mean().sort_values(ascending=False).reset_index()

fig = px.bar(
    df_media_salario_pais,
    x='empresa',
    y='usd',
    title='Salário Médio de Data Scientists por País (USD)',
    labels={'empresa': 'Localização da Empresa (País)', 'usd': 'Salário Médio Anual (USD)'},
    color='empresa',
    category_orders={'empresa': df_media_salario_pais['empresa'].tolist()}
)
fig.show()

df.head()

pip install pycountry

import pycountry

# Função para converter ISO-2 para ISO-3
def iso2_to_iso3(code):
    try:
        return pycountry.countries.get(alpha_2=code).alpha_3
    except:
        return None

# Criar nova coluna com código ISO-3
df_tratado['residencia_iso3'] = df_tratado['residencia'].apply(iso2_to_iso3)

# Calcular média salarial por país (ISO-3)
df_ds = df_tratado[df_tratado['cargo'] == 'Data Scientist']
media_ds_pais = df_ds.groupby('residencia_iso3')['usd'].mean().reset_index()

# Gerar o mapa
fig = px.choropleth(media_ds_pais,
                    locations='residencia_iso3',
                    color='usd',
                    color_continuous_scale='rdylgn',
                    title='Salário médio de Cientista de Dados por país',
                    labels={'usd': 'Salário médio (USD)', 'residencia_iso3': 'País'})

fig.show()

df_tratado.head()

df_tratado.to_csv('dados-imersao-final.csv', index=False)